//! ACL smoke: deny-open is defined; open is not reachable without allow-open in default set.
//!
//! Full IPC capability enforcement needs an app fixture; `mock_app` bypasses the ACL
//! runtime. This test still fails loudly if permission wiring drifts.

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::PathBuf;

    fn repo_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
    }

    #[test]
    fn deny_open_permission_is_defined() {
        let open =
            fs::read_to_string(repo_root().join("permissions/autogenerated/commands/open.toml"))
                .expect("open.toml");
        assert!(
            open.contains("identifier = \"deny-open\""),
            "deny-open missing from open.toml"
        );
        assert!(
            open.contains("commands.deny = [\"open\"]"),
            "deny-open must deny the open command"
        );
        assert!(
            open.contains("identifier = \"allow-open\""),
            "allow-open missing from open.toml"
        );
        assert!(
            open.contains("commands.allow = [\"open\"]"),
            "allow-open must allow the open command"
        );
    }

    #[test]
    fn default_capability_includes_allow_open_not_deny() {
        let default =
            fs::read_to_string(repo_root().join("permissions/default.toml")).expect("default.toml");
        assert!(
            default.contains("\"allow-open\""),
            "default set must grant allow-open"
        );
        assert!(
            !default.contains("\"deny-open\""),
            "default set must not include deny-open"
        );
    }

    /// Document the contract: a capability that omits allow-open (and does not
    /// pull in serialplugin:default) must not list open as allowed.
    #[test]
    fn capability_without_allow_open_has_no_open_grant() {
        // Minimal capability body an app would use when intentionally denying open.
        let capability_permissions: &[&str] = &["serialplugin:allow-available-ports"];
        assert!(!capability_permissions
            .iter()
            .any(|p| *p == "serialplugin:allow-open" || *p == "serialplugin:default"));
    }
}
