#!/usr/bin/env bash
# Sync stable Android integration tests into Tauri gen/android (regenerated by tauri android init).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INTEGRATION="$ROOT/examples/serialport-test/android-integration"
DEST="$ROOT/examples/serialport-test/src-tauri/gen/android/app/src/androidTest"
APP_GRADLE="$ROOT/examples/serialport-test/src-tauri/gen/android/app/build.gradle.kts"
GRADLE_MARKER="JNI integration test deps (sync-android-integration-tests.sh)"

if [[ ! -d "$INTEGRATION/src/androidTest" ]]; then
  echo "error: missing $INTEGRATION/src/androidTest" >&2
  exit 1
fi

if [[ ! -d "$(dirname "$DEST")" ]]; then
  echo "error: run 'pnpm tauri android build' first to generate gen/android" >&2
  exit 1
fi

echo "Syncing androidTest sources → $DEST"
rm -rf "$DEST"
mkdir -p "$DEST/kotlin"
cp -R "$INTEGRATION/src/androidTest/"* "$DEST/"

echo "Syncing instrumented fake (FakeUsbSerialPort from android-integration/fakes)"
mkdir -p "$DEST/kotlin/app/tauri/serialplugin/manager"
cp "$INTEGRATION/fakes/FakeUsbSerialPort.kt" \
  "$DEST/kotlin/app/tauri/serialplugin/manager/"

# Gradle patch is optional legacy; FakeUsb no longer needs mockito / JVM 11 for androidTest.
if [[ -f "$APP_GRADLE" ]] && ! grep -q "$GRADLE_MARKER" "$APP_GRADLE"; then
  echo "Note: no Gradle patch required (FakeUsb uses Parcel stubs, JVM 1.8 compatible)"
fi

echo "Done."
